name: covid-main

channels:
  - conda-forge
  - defaults
  - opensourceeconomics

dependencies:

  - python=3.7
  - pip=19.0.3
  - jupyterlab
  - nbsphinx
  - pdbpp
  - sphinx
  - pip:
    - black
    - blackcellmagic
    - pre-commit
