name: covid-main

channels:
  - conda-forge
  - defaults
  - opensourceeconomics

dependencies:

  - python=3.7
  - pip=19.0.3
  - pandas>=1.0
  - numpy
  - scipy
  - seaborn>=0.10
  - jupyterlab
  - nbsphinx
  - pdbpp
  - sphinx=2.4.4
  - mock
  - nose
  - scikit-learn
  - xlrd
  - conda-build
  - anaconda-client
  - panel>=0.9.2
  - bokeh>=2.0
  - plotly>=4.5
  - pip:
    - black
    - blackcellmagic
    - pre-commit




